"""Generate a copyright-free synthetic "yellowed scan" PDF for testing.

    python samples/make_sample.py [pages] [out.pdf]

Each page: cream/yellow paper with uneven lighting, faint gray text,
noise, and a small skew, rendered at 150 dpi.
"""
from __future__ import annotations

import io
import os
import random
import sys

import numpy as np
import pymupdf
from PIL import Image, ImageDraw, ImageFont

LINES = [
    "This sample page is generated by scan-pdf-cleanup for testing.",
    "It imitates an old book scan: yellow paper, faint ink, a tilt.",
    "The quick brown fox jumps over the lazy dog. 0123456789",
    "Whiten the background, darken the text, straighten the page.",
    "No copyrighted material is included in this file.",
    "Read it on a black-and-white e-reader after cleanup.",
]


def make_page(w: int, h: int, index: int, rng: random.Random) -> Image.Image:
    # uneven yellowish paper
    y, x = np.mgrid[0:h, 0:w].astype(np.float32)
    shade = 1.0 - 0.18 * (x / w) - 0.10 * (y / h)
    base = np.array([228, 214, 172], dtype=np.float32)  # cream
    paper = base[None, None, :] * shade[..., None]
    noise = rng.uniform(-6, 6)
    paper += np.random.default_rng(index).normal(0, 7, size=paper.shape) + noise
    img = Image.fromarray(np.clip(paper, 0, 255).astype(np.uint8), "RGB")

    draw = ImageDraw.Draw(img)
    try:
        font = ImageFont.load_default(size=22)
        big = ImageFont.load_default(size=34)
    except TypeError:  # very old Pillow
        font = big = ImageFont.load_default()
    ink = (95, 90, 88)  # faint gray-brown ink
    draw.text((120, 90), f"Chapter {index + 1}", font=big, fill=(70, 66, 64))
    yy = 170
    for k in range(28):
        line = LINES[(k + index) % len(LINES)]
        draw.text((120, yy), line, font=font, fill=ink)
        yy += 40
    draw.text((w // 2 - 15, h - 80), str(index + 1), font=font, fill=ink)

    angle = rng.uniform(-2.0, 2.0)
    return img.rotate(angle, resample=Image.BICUBIC, expand=False, fillcolor=(200, 190, 160))


def main() -> None:
    pages = int(sys.argv[1]) if len(sys.argv) > 1 else 3
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "sample_yellow_scan.pdf")
    rng = random.Random(42)
    dpi = 150
    w, h = int(5.8 * dpi), int(8.3 * dpi)  # A5-ish
    doc = pymupdf.open()
    for i in range(pages):
        img = make_page(w, h, i, rng)
        buf = io.BytesIO()
        img.save(buf, "JPEG", quality=80)
        page = doc.new_page(width=w * 72 / dpi, height=h * 72 / dpi)
        page.insert_image(page.rect, stream=buf.getvalue())
    doc.save(out, deflate=True)
    doc.close()
    print(out)


if __name__ == "__main__":
    main()
